# Generated by Django 3.0.1 on 2020-04-14 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_mosuser_vkid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mosuser',
            name='vkId',
        ),
    ]
