# Generated by Django 3.0.1 on 2020-04-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_remove_mosuser_vkid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mosuser',
            name='mosPassword',
        ),
        migrations.AddField(
            model_name='mosuser',
            name='mosPasswordCiphertext',
            field=models.BinaryField(blank=True, max_length=100, verbose_name='Mos.ru password encrypted ciphertext'),
        ),
        migrations.AddField(
            model_name='mosuser',
            name='mosPasswordNonce',
            field=models.BinaryField(blank=True, max_length=100, verbose_name='Mos.ru password encrypted nonce'),
        ),
        migrations.AddField(
            model_name='mosuser',
            name='mosPasswordTag',
            field=models.BinaryField(blank=True, max_length=100, verbose_name='Mos.ru password encrypted tag'),
        ),
    ]
